modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="big_addon"
version="0.1.1"
displayName="WorldStudios' Big Java Addon"
displayURL="https://theworldstudiosweb.wordpress.com"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="WorldStudios"
description="Adds a bunch of random stuff to minecraft java like an ender helmet and a biome full of waste."
enumExtensions="META-INF/enumextensions.json"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.big_addon]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.big_addon]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration